### ISSUE TITLE
The problem of embedding

### ISSUE THREAD

**Issue by 1054651112** [filby89/NTUA-BEEU-eccv2020#2]
I'm very sorry. I want to ask a question about the code. In the models.py, I'm a little confused about line 203. The dimension of embed_segm should be (32, 300), but after the following operation: 

embed = embed_segm.view((-1, self.num_segments) + embed_segm.size()[1:])

I tested it and found that the dimensions did not match. Did I understand it wrong?

**Comment by filby89** [comment]
Hi,
the dimensions should correctly be (-1, self.num_segments, 300), since we need to get an embedding for each segment, and then use consensus to obtain embedding for the whole video.

**Comment by ifei17-hfut** [comment]
Hi, I would like to ask you a question. How did you get the [glove_840B_embeddings.npy] in the file you provided? How do I get such a file on another dataset?

**Comment by filby89** [comment]
Hi, 
you can download the pretrained word embeddings from https://nlp.stanford.edu/projects/glove/. Then, you can search inside the file and keep only the embeddings for your dataset.

Example:

```python
import re

line_embeddings = []

for i,emotion in enumerate(bold.categorical_emotions+bold.continuous_emotions):
    file = open("/gpu-data/filby/glove.840B.300d.txt", "r")
    found = False

    for line in file:
        if re.search(emotion.lower() + " ", line):
            line_embeddings.append(line.strip())
            found = True
            break
        
    if not found:
        print(emotion)
    file.close()
```

**Comment by ifei17-hfut** [comment]
Very interesting job!
Can you use a network disk to share the Bold dataset? I can't register an account on the official website of BOLD. I can send you the agreement to you through the email. If you can, you can send me an email to me. My mailbox address is: jiafei127@gmail.com
Thank you! Looking forward to your reply.

**Comment by filby89** [comment]
Hey,
sadly I am not directly related with the authors that published the BOLD dataset and thus am not legally allowed to share the dataset. I would suggest you to email Professor Wang: http://wang.ist.psu.edu/docs/home.shtml
